name: travel_together
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  lottie: ^3.1.0
  animated_splash_screen: ^1.3.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  intl: ^0.19.0
  flutterfire_cli: ^0.1.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/